# Generated by Django 5.2.12 on 2026-03-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(max_length=64)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("label", models.CharField(max_length=16)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("scored_at", models.DateTimeField()),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_score",
                        to="returns.returncase",
                    ),
                ),
            ],
            options={
                "ordering": ["-scored_at", "id"],
            },
        ),
    ]
